<a href="https://colab.research.google.com/github/UCDAyoung/DataAnalysisProgramming/blob/main/hwOfLecture2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(0)

# NumPy Exercises!
Complete the solution code to have a desired output.

**[Caution!]** Not allow to use iteration, such as for-loop.





### 1. Create a 4×4 numpy array of all True boolean’s 

In [ ]:
# Input
arr_size = (4, 4)

# Solution
bool_arr = np.full(arr_size,True,dtype=bool)

# Print
print(bool_arr)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


### 2. Extract all odd numbers from given `arr`

In [ ]:
# Input
arr = np.arange(30)

# Solution
arr = arr[np.array([False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True])]

# Print
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]


### 3. Get the positions where elements of `a` and `b` match
(hint, refer [np.where](https://numpy.org/doc/stable/reference/generated/numpy.where.html).)



In [120]:
# Input
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Solution
idx = np.where(a==b)

# Print
print(idx)
#(array([1, 3, 5, 7]),)

(array([1, 3, 5, 7]),)


### 4. Find the mean, median, standard deviation of iris's `sepallength` (1st column).

In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
mu = np.mean(sepallength,axis=0)
med = np.median(sepallength,axis=0)
std = np.std(sepallength,axis=0)


# Print
print(mu, med, std)

5.843333333333334 5.8 0.8253012917851409


### 5. Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False.
(hint, refer [np.unique](https://numpy.org/doc/stable/reference/generated/numpy.unique.html).)

In [ ]:
# Input
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)

# Solution
## Create an all True array
out = np.full(a.size,True,dtype=bool)

#bool onoff 100만들어서, 해당 인덱스를 거칠 때 true이면 out을 false로 바꿔준다. trueaus 
onoff = [bool] 
for i in range(100):
  onoff.append(True)

for i in range(len(a)):
  if onoff[a[i]]:
    onoff[a[i]] = False 
    out[i] = False

## Find the index positions of unique elements
#unique_positions = 

## Mark those positions as False
#out[unique_positions] 

print('Duplicate entrie: ', out)
##answer
#Array:  [0 0 3 0 2 4 2 2 2 2]
#Duplicate entrie:  [False  True False  True False False  True  True  True  True]

Array:  [0 0 3 0 2 4 2 2 2 2]
Duplicate entrie:  [False  True False  True False False  True  True  True  True]


# Pandas Exercises!
Complete the solution code to have a desired output. 





### 6. Combine `ser1` and `ser2` to form a dataframe.

In [ ]:
# Input
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

ser1
ser2
# Solution 
d = {'col1' : ser1,'col2' : ser2}
df = pd.DataFrame(data=d)

# Print
print(df.head())

#answer 
#col1 col2
#0 a 0
#1 b 1
#2 c 2
#3 d 3
#4 e 4 


  col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4


### 7. Check if `df` has any missing values.

In [ ]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.head())

# Solution
isNull = df.isnull().values.any()

print('\nIs there any missing value?: %s' %isNull)
# Answer 
#  Manufacturer    Model     Type  ...  Weight   Origin           Make
#0        Acura  Integra    Small  ...  2705.0  non-USA  Acura Integra
#1          NaN   Legend  Midsize  ...  3560.0  non-USA   Acura Legend
#2         Audi       90  Compact  ...  3375.0  non-USA        Audi 90
#3         Audi      100  Midsize  ...  3405.0  non-USA       Audi 100
#4          BMW     535i  Midsize  ...  3640.0  non-USA       BMW 535i
#[5 rows x 27 columns]
#Is there any missing value?: True


  Manufacturer    Model     Type  ...  Weight   Origin           Make
0        Acura  Integra    Small  ...  2705.0  non-USA  Acura Integra
1          NaN   Legend  Midsize  ...  3560.0  non-USA   Acura Legend
2         Audi       90  Compact  ...  3375.0  non-USA        Audi 90
3         Audi      100  Midsize  ...  3405.0  non-USA       Audi 100
4          BMW     535i  Midsize  ...  3640.0  non-USA       BMW 535i

[5 rows x 27 columns]

Is there any missing value?:True


### 8. Create a TimeSeries starting `2021-01-01` and 10 weekends (sundays) after that **having** random numbers as values?

In [111]:
# Solution
ser = pd.Series(pd.date_range(start='2021-01-01',periods=10,freq='W'))
print(ser)
#0   2021-01-03
#1   2021-01-10
#2   2021-01-17
#3   2021-01-24
#4   2021-01-31
#5   2021-02-07
#6   2021-02-14
#7   2021-02-21
#8   2021-02-28
#9   2021-03-07
#dtype: datetime64[ns] :  얘는 왜나오는거지?

0   2021-01-03
1   2021-01-10
2   2021-01-17
3   2021-01-24
4   2021-01-31
5   2021-02-07
6   2021-02-14
7   2021-02-21
8   2021-02-28
9   2021-03-07
dtype: datetime64[ns]


### 9. In `df`, compute the mean price of every fruit using grouping function.

In [ ]:
#참고사이트 : https://rfriend.tistory.com/383 , http://doc.mindscale.kr/km/python/12.html
# Input
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
print(df)
# Solution
#1. fruit mean 값을 찾는다. 
#2. price만 뽑는다.
df2 = df.groupby(['fruit']).mean()
df2['price']


# Answer
#fruit
#apple     5.666667
#banana    7.333333
#orange    7.000000
#Name: price, dtype: float64

    fruit    rating  price
0   apple  0.657292      2
1  banana  0.896313      6
2  orange  0.476488      3
3   apple  0.977116     14
4  banana  0.951210      3
5  orange  0.948137      6
6   apple  0.607276     12
7  banana  0.869623      0
8  orange  0.775413      6


fruit
apple     9.333333
banana    3.000000
orange    5.000000
Name: price, dtype: float64

### 10. Join two dataframes `df1` and `df2` for intersection items on `use_id`.
For `df2`, please select only `use_id`, `platform`, `device` columns not all columns for merging.

In [119]:
# 몰랐던 것들 
#column 선택해서 출력하기
#merge 관련 

# Input
base_path = 'https://raw.githubusercontent.com/shanealynn/Pandas-Merge-Tutorial/master/'
df1 = pd.read_csv(base_path + 'user_usage.csv')
df2 = pd.read_csv(base_path + 'user_device.csv')

# Solution
df2 = pd.DataFrame(df2,columns = ['use_id','platfrom','device'])
df_right = pd.merge(df1,df2,on='use_id',how='right')
df_right


outgoing_mins_per_month  ...                  device
0                        NaN  ...               iPhone7,2
1                        NaN  ...                 Nexus 5
2                        NaN  ...                SM-G903F
3                        NaN  ...               iPhone7,2
4                        NaN  ...               ONE E1003
..                       ...  ...                     ...
267                   344.53  ...                SM-G900F
268                      NaN  ...               iPhone7,2
269                      NaN  ...               iPhone7,2
270                      NaN  ...               iPhone8,4
271                    42.75  ...  Vodafone Smart ultra 6

[272 rows x 6 columns]